### PR TITLE
Mavenize

### PR DESCRIPTION
**Pull request by rpardini**
It should address #1 
I added a fake "IntegrationTest" (copied from Demo.asciidoc) that doesn't actually test anything without human input and so can be ignored.

### CODE REVIEW

**Comment by gjoseph** [comment]
Thanks a lot ! I actually have the same locally, not pushed, because I wanted to figure out the license issues first.

**Comment by gjoseph** [comment]
Fixed with d6755c071e, thanks again. Let me know if you think anything's missing. I'll try to cut a release soon, but still need to go through licensing (#2) once more, since some code was copied off of OpenJDK, it seems it might be a little delicate.

**Comment by rpardini** [comment]
Yeah, thanks. I wanted to investigate performance and mavenization was a prereq.
I did not find performance to be that much better than JDK7+, and probably not worth the trouble.
Maybe JDK7+ uses similar code already, and it's Apple's fault for the slowness, I wonder?
In any case I agree this should probably be Apache v2...

**Comment by gjoseph** [comment]
Hmm, tbh I haven't tested the project since Mavenizing, but it _should_ work better than JDK7. On OSX, JDK7 has no native filesystem watch mechanism, so it relies on polling, and polls the watch keys, IIRC every 10 seconds. Almost instantaneous with BarbaryWatchService. I'll def make sure to add proper testing before releasing. Yesterday I was focusing on getting Travis to deploy snapshots to sonatype; almost there, as soon as I managed to convince Travis to build it on osx.

**Pull request closed without merging**
