### PR TITLE
Brought in line with jdk, removed replicated classes

### PR DESCRIPTION
**Pull request by masc3d**
I needed this for abstraction across platforms/native watch service implementations. Conformed all code and test cases and verified the demo works.

### CODE REVIEW

**Comment by leppert** [comment]
@gjoseph +1 for seeing this in the Central Maven repo.

**Comment by zbentley** [comment]
Also +1. This would be incredibly useful for testing things that eventually target Linux on my OSX development system!

**Comment by zbentley** [comment]
I hate to nag, but is there any chance this will merge?

**Comment by gjoseph** [comment]
@zbentley sorry - I have completely lost track of this project, as I haven't been using/needing it for several years now (which is a shame, as I hoping to revive it a little bit after it was abandoned by the previous maintainer as well).
Happy to merge this if that that helps, but I'd rather someone else take the responsibility of releasing new versions if they are so inclined. You might also want to look at alternatives like https://github.com/takari/directory-watcher

**Comment by gjoseph** [comment]
Hi @masc3d @zbentley @leppert sorry for the slow response -- as you may have gathered, I haven't had capacity to maintain this project in a long time. I'm finally officially retiring it. See README for possible alternatives, if you're still needing this. ✌️

**Comment by zbentley** [comment]
@gjoseph no worries, thanks for all the excellent work!

**Pull request closed without merging**
